### ISSUE TITLE
www.seedtool.info should support ssl and redirect to seedtool.info

### ISSUE THREAD

**Issue by Sjlver** [BlockchainCommons/seedtool.info#11]
When browsing https://www.seedtool.info/, users see the following if they have strict HTTPS enabled in their browser:

![image](https://user-images.githubusercontent.com/72059/161926489-8c8b4815-eba9-464b-94fc-c10959b34bb7.png)

We should:
1. Make sure that the SSL certificate also covers the www. subdomain
2. Make the www. subdomain redirect to the canonical https://seedtool.info

Assigning to @shannona to take a look.

**Comment by ChristopherA** [comment]
The certificate is generated by GitHub with Let’s Encrypt. I don’t believe we have any control over it. 

I think the configuration of Lifehash.info needs to be matched.

**Comment by shannona** [comment]
I think I need to set the www to forward to @ rather than them both being
CNames. Bizarre, but should be easy enough. On my list for today.

**Comment by shannona** [comment]
It turns out that (1) seedtool.info was set up exactly the same as lifehash.info, with a Cname for both @ and www; and (2) the problem self-corrected.

So, I assume that GitHub was just lagging on the Let's Encrypt cert for some reason. But it all looks good now.

**Comment by shannona** [comment]
OK, not self-corrected. But they are set up just the same, so more investigations required ...

**Comment by shannona** [comment]
Alright, I had to kick it a few times to recheck the DNS. I also checked off the require HTTPS box, which is now available.

Bottom line: http{s}://{www.}seedtool.info should now all redirect to https://seedtool.info, which has a valid cert.
