### ISSUE TITLE
Rename branch `master` -> `main`

### ISSUE THREAD

**Issue by Sjlver** [BlockchainCommons/seedtool.info#3]
It's all in the subject line; I just don't have the necessary privileges on the repo.

Branch `main` is already created and up-to-date with `master`. The only task left to do is to delete `master` and configure GitHub to use `main` as the default branch. @ChristopherA  or @shannona, It would be nice if you could do that.

Why we do this: https://sfconservancy.org/news/2020/jun/23/gitbranchname/

**Comment by ChristopherA** [comment]
It looks like what GitHub wants to do is rename master to main and make it default in a single operation.

![file apr 02, 9 55 31 pm](https://user-images.githubusercontent.com/69103/161412185-b695c817-6599-4de6-b25c-f790f6d3fa00.jpeg)

**Comment by ChristopherA** [comment]
![Uploading file apr 02, 9 58 18 pm.jpeg…]()

**Comment by ChristopherA** [comment]
When click on edit default branch you get a rename dialogue.

![file apr 02, 9 58 18 pm](https://user-images.githubusercontent.com/69103/161412401-5f4041f7-d1aa-4d2e-aea8-11765db8a843.jpeg)

**Comment by Sjlver** [comment]
Ah... sorry didn't know that. I've deleted the `main` branch, so you should be able to go ahead.

**Comment by Sjlver** [comment]
... and done with my new admin privileges :)
