### ISSUE TITLE
Publish /docs/ to seedtool.info via GitHub pages

### ISSUE THREAD

**Issue by Sjlver** [BlockchainCommons/seedtool.info#5]
See https://github.com/BlockchainCommons/seedtool.info/pull/4

I need someone with repository admin privileges to set up GitHub pages, so that it publishes the contents of /docs/ to https://seedtool.info.

**Comment by ChristopherA** [comment]
I’ve set it to main /docs/, but the solution to the master problem may require main to be deleted and master renamed to main, so this may need to be done again.

**Comment by ChristopherA** [comment]
@Sjlver I’ve set you as admin for now so you can puzzle through these.

**Comment by Sjlver** [comment]
Thanks!

I was able to configure GitHub pages. Nothing is there yet until #4 is merged.

With the current settings, the page will be published at https://blockchaincommons.github.io/seedtool.info/. I think that only an org-wide admin can change that.

**Comment by shannona** [comment]
I believe everything is now working as seedtool.info or www.seedtool.info
